config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :blogs do
    collection do
      post :confirm

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user,optional: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :title, length: {in: 1..140}
  validates :content, length: {in: 1..140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/score.rb
class Score < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy ]
  before_action :set_current_user, only: [:new, :edit, :show]

  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def create 
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    # 画像保存（create）の際に、キャッシュから画像を復元してから保存する
    @blog.image.retrieve_from_cache! params[:cache][:image] if params[:cache][:image].present?
    # @picture.image.retrieve_from_cache! params[:cache][:image]
    # @picture.save!
    # @blog.image.cache! 画像なしの投稿の際にエラーになったので外して様子見。動作したのでコメントアウト。
    @blog.save!
    if @blog.save
    # 投稿完了メールを送信
      BlogMailer.blog_mail(@blog).deliver
    # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
    # 入力フォームを再描画します。
      render 'new'
    end
  end

  def show
    @blog = Blog.find(params[:id])
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image )
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def set_current_user
    unless logged_in?
    flash[:warning] = 'ログインして下さい'
    redirect_to new_session_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ログイン成功した場合
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      # ログイン失敗した場合
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites_blogs = @user.favorites
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit )  do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image, id: :feed_image %>
  <%= form.hidden_field :image_cache %>
  </div>

  <%= form.submit '送信', class: 'btn btn-default' %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<div class="container">
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= image_tag(@blog.image.url , :size => "300x200") unless @blog.image.blank? %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
  <p><%= form.submit  "登録する" %></p>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p><%= form.submit "もどる" %></p>
<% end %>

</div>

app/views/blogs/edit.html.erb
<div class="container">
<h2>ブログを編集する</h2>

  <%= render 'form' %>
</div>

app/views/blogs/index.html.erb
<div class="container">
    <nav class="article">

<h1>ブログ一覧</h1>

<p><%= notice %></p>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>投稿者</th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= blog.user.name %></td>
    <td><%= link_to '　詳細　', blog_path(blog.id) %></td>
    <% if logged_in? && blog.user_id == current_user.id %>
    <td><%= link_to '　編集　', edit_blog_path(blog.id) %></td>
    <td><%= link_to '　削除　', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    <% else %>
    <% end %>

  </tr>
<% end %>
</table>

<br>

<%= link_to 'ブログ新規作成画面へ', new_blog_path %>

            <article>
                <ul class="row">
                  <li class="col-sm-6 col-md-4"><%= image_tag '300x300_01.jpg' ,:size => "200x200" %></li>
                  <li class="col-sm-6 col-md-4"><%= image_tag '300x300_02.jpg' ,:size => "200x200" %></li>
                  <li class="col-sm-6 col-md-4"><%= image_tag '300x300_03.jpg' ,:size => "200x200" %></li>
                </ul>
            </article>
            <article>
                <ul class="row">
                  <li class="col-sm-6 col-md-4"><%= image_tag '300x300_04.jpg' ,:size => "200x200" %></li>
                  <li class="col-sm-6 col-md-4"><%= image_tag '300x300_05.jpg' ,:size => "200x200" %></li>
                  <li class="col-sm-6 col-md-4"><%= image_tag '300x300_06.jpg' ,:size => "200x200" %></li>
                </ul>
            </article>

    </nav>
</div>

app/views/blogs/new.html.erb
<div class="container">
<h2>ブログを作成する</h2>

  <%= render 'form' %>
</div>

app/views/blogs/show.html.erb
<div class="container">
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<p>投稿者: <%= @blog.user.name %></p>
<p><%= image_tag @blog.image ,:size => "300x200" %></p>

<% unless @blog.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-prymary' %>
  <% end %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phase3 Association Task</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">ナビゲーション</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/blogs">Task</a>
        </div>

        <div class="collapse navbar-collapse" id="gnavi">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/blogs" class="btn btn-default"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>BLOG一覧</a></li>
              <li><a href="/blogs/new" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>新規投稿</a></li>
              <li><a href="/blogs/sessions/new" class="btn btn-default"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>ログイン</a></li>
              <li><a href="/blogs/users/new" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>新規登録</a></li>
            </ul>
        </div>

      </div>
    </nav>
    
      <div class="container">
          <section class="main-header">
            <%= image_tag 'thisheat.jpg',:size => "300x200" %>
          </section>

          <section class="about">
            <h1>About Blogs</h1>
              <p>
                画像UPLOADシステムシリーズ課題で作成するアプリです。<br>
              </p>
          </section>

        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>

        <% if logged_in? %>
          <%= link_to "Profile", user_path(current_user.id) %>
          <%= link_to "Logout", session_path(current_user.id), method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Login", new_session_path %>
        <% end %>

        <%= yield %>
      </div>

      <footer>
        <p>2018 knittkg</p>
      </footer>
  </body>
</html>

app/views/stocks/index.html.erb
<h1>Stocks#index</h1>
<p>Find me in app/views/stocks/index.html.erb</p>

app/views/users/new.html.erb
<div class="container">
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
<div class="user_name">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="user_email">
  <%= f.label :email %>
  <%= f.email_field :email %>
</div>
<div class="user_password">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div class="user_password_conformation">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
<div class="user_icon">
  <%= f.label :image %>
  <%= f.file_field :image, id: :feed_image %>
  <%= f.hidden_field :image_cache %>
</div>

  <%= f.submit '新規登録', class: 'btn btn-default' %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
<h1><%= @user.name %>のページ</h1>
<p><%= image_tag @user.image ,:size => "50x50" %></p>
<p>メールアドレス: <%= @user.email %></p>

<p>お気に入りBLOG一覧</p>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>投稿者</th>
  </tr>

<% @favorites_blogs.each do |favorite_blog| %>
  <tr>
    <td><%= favorite_blog.blog.title %></td>
    <td><%= favorite_blog.blog.content %></td>
    <td><%= favorite_blog.blog.user.name %></td>
    <td><%= link_to '　詳細　', blog_path(favorite_blog.blog.id) %></td
  </tr>
<% end %>
</table>
</div>